name: Deploy to Onion server email service
on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_INSTANCE_SG_ID: ${{ secrets.EC2_SG_ID }}

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get runner IP address
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Whitelist runner IP address
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id $AWS_INSTANCE_SG_ID \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32
            
      - name: Deploy to Server        
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ONION_SERVER }}
          username: ${{ secrets.ONION_USERNAME }}
          key: ${{ secrets.ONION_KEY }}
          port: ${{ secrets.ONION_PORT }}
          script: |
            cd /var/www/OnionEmailService/
            git pull
            npm install
            pm2 restart 3

      - name: Revoke runner IP address
        if: ${{ always() }}
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id $AWS_INSTANCE_SG_ID \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32
